version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - mysql
            - mongo
        entrypoint: ["/var/www/docker/entrypoint.sh"]

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: news_aggregator
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - laravel
        volumes:
            - mysql_data:/var/lib/mysql

    mongo:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - laravel
    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_scheduler
        depends_on:
            - app
            - mysql
            - mongo
        volumes:
            - .:/var/www
        command: >
            sh -c "while [ true ]; do php artisan schedule:run --no-interaction & sleep 60; done"
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
    mongo_data:
